version: '3'
services:
  database:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sikoba-db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: postgres://postgres:postgres@database:5432/sikoba-db
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge

volumes:
  data:
